// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://koboymestefqymmeemae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvYm95bWVzdGVmcXltbWVlbWFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MjE4NTAsImV4cCI6MjA2MDM5Nzg1MH0.IKxHHyAEeIuSfsFAdOs3M1FtItxJJaTkoLYvIMFL960";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);